import React from 'react'

/**
 * Carries the id generated by FieldRow down to whichever control it wraps, so
 * the label can point at it with htmlFor without every call site having to
 * invent and thread an id.
 */
const FieldIdContext = React.createContext<string | undefined>(undefined)

/** Controls call this to adopt the id their surrounding FieldRow label targets. */
export function useFieldId(explicitId?: string): string | undefined {
  const inherited = React.useContext(FieldIdContext)
  return explicitId ?? inherited
}

interface SettingsSectionProps {
  icon: React.ReactNode
  title: string
  description?: string
  children: React.ReactNode
}

/**
 * Reusable section wrapper for the Settings view.
 * Renders a titled card with a divider and slotted content.
 */
export default function SettingsSection({
  icon,
  title,
  description,
  children
}: SettingsSectionProps) {
  return (
    <div style={{
      background: 'var(--color-surface-1)',
      border: '1px solid var(--color-surface-offset)',
      borderRadius: 'var(--radius-lg)'
    }}>
      {/* Section header */}
      <div style={{
        padding: 'var(--space-4) var(--space-5)',
        borderBottom: '1px solid var(--color-surface-offset)',
        display: 'flex',
        alignItems: 'center',
        gap: 'var(--space-3)',
        background: 'var(--color-surface-2)'
      }}>
        <span aria-hidden="true" style={{ color: 'var(--color-secondary)', display: 'flex', flexShrink: 0 }}>
          {icon}
        </span>
        <div style={{ flex: 1, minWidth: 0 }}>
          {/* A real heading: these were <div>s, so the Settings page presented
              screen readers with no document outline to navigate by. */}
          <h2 style={{
            fontSize: 'var(--text-xs)',
            fontWeight: 'var(--weight-bold)',
            color: 'var(--color-text-base)',
            textTransform: 'uppercase',
            letterSpacing: 'var(--tracking-wide)',
            margin: 0
          }}>
            {title}
          </h2>
          {description && (
            <div style={{
              fontSize: 'var(--text-xs)',
              color: 'var(--color-text-faint)',
              marginTop: '2px'
            }}>
              {description}
            </div>
          )}
        </div>
      </div>

      {/* Section body */}
      <div style={{ padding: 'var(--space-5)' }}>
        {children}
      </div>
    </div>
  )
}

// Shared utility styles

export function FieldRow({
  label,
  hint,
  children
}: {
  label: string
  hint?: string
  children: React.ReactNode
}) {
  // The label used to be a bare <label> sibling of the control: not clickable,
  // and announced by screen readers as unassociated text, so every field in
  // Settings was effectively unlabelled. The id is published through context so
  // the control inside can claim it.
  const fieldId = React.useId()
  const hintId = `${fieldId}-hint`

  return (
    <div style={{
      display: 'flex',
      flexDirection: 'column',
      gap: 'var(--space-1-5)'
    }}>
      <label
        htmlFor={fieldId}
        style={{
          fontSize: 'var(--text-xs)',
          fontWeight: 'var(--weight-semibold)',
          color: 'var(--color-text-muted)',
          width: 'fit-content',
          cursor: 'pointer'
        }}
      >
        {label}
      </label>
      <FieldIdContext.Provider value={fieldId}>
        {children}
      </FieldIdContext.Provider>
      {hint && (
        <span
          id={hintId}
          style={{
            fontSize: '11px',
            color: 'var(--color-text-faint)'
          }}
        >
          {hint}
        </span>
      )}
    </div>
  )
}

export function SettingsInput({
  value,
  onChange,
  onBlur,
  placeholder,
  type = 'text',
  id,
  min,
  max,
  step,
  inputMode,
  /** Off for anything machine-shaped: endpoints, model ids, keys, ports. */
  spellCheck = false,
  ariaLabel
}: {
  value: string | number
  onChange: (v: string) => void
  onBlur?: () => void
  placeholder?: string
  type?: string
  id?: string
  min?: number
  max?: number
  step?: number
  inputMode?: 'text' | 'numeric' | 'decimal' | 'url' | 'email'
  spellCheck?: boolean
  ariaLabel?: string
}) {
  const fieldId = useFieldId(id)
  return (
    <input
      id={fieldId}
      type={type}
      value={value}
      onChange={e => onChange(e.target.value)}
      onBlur={onBlur}
      placeholder={placeholder}
      min={min}
      max={max}
      step={step}
      inputMode={inputMode}
      spellCheck={spellCheck}
      // Settings fields are app configuration, not credentials a password
      // manager should be offering to fill.
      autoComplete="off"
      aria-label={ariaLabel}
      style={{
        background: 'var(--color-surface-2)',
        border: '1px solid var(--color-surface-offset)',
        color: 'var(--color-text-base)',
        borderRadius: 'var(--radius-md)',
        padding: 'var(--space-2) var(--space-3)',
        fontSize: 'var(--text-sm)',
        width: '100%',
        fontFamily: 'var(--font-sans)',
        transition: 'border-color 100ms ease'
        // No `outline: none` here. As an inline style it outranks the
        // stylesheet, so it silently disabled the app's global
        // :focus-visible ring on every field in Settings.
      }}
      onFocus={e => (e.currentTarget.style.borderColor = 'var(--color-primary)')}
      onBlurCapture={e => (e.currentTarget.style.borderColor = 'var(--color-surface-offset)')}
    />
  )
}

export function ToggleSwitch({
  checked,
  onChange,
  disabled = false,
  label
}: {
  checked: boolean
  onChange: (v: boolean) => void
  disabled?: boolean
  /** Accessible name. The switch renders no text, so without it screen readers announce nothing. */
  label?: string
}) {
  return (
    <button
      role="switch"
      aria-checked={checked}
      aria-label={label}
      disabled={disabled}
      onClick={() => !disabled && onChange(!checked)}
      style={{
        width: '36px',
        height: '20px',
        borderRadius: '10px',
        background: checked ? 'var(--color-secondary)' : 'var(--color-surface-offset)',
        border: 'none',
        cursor: disabled ? 'default' : 'pointer',
        position: 'relative',
        transition: 'background 150ms ease',
        flexShrink: 0,
        opacity: disabled ? 0.5 : 1
      }}
    >
      <div style={{
        position: 'absolute',
        top: '3px',
        left: '3px',
        width: '14px',
        height: '14px',
        borderRadius: '50%',
        background: checked ? 'var(--color-text-inverted)' : 'var(--color-text-faint)',
        // translateX rather than animating `left`: transform is composited, so
        // the knob does not force layout on every frame of the toggle.
        transform: checked ? 'translateX(16px)' : 'translateX(0)',
        transition: 'transform 150ms ease, background 150ms ease'
      }} />
    </button>
  )
}

export function Divider() {
  return (
    <div style={{
      height: '1px',
      background: 'var(--color-surface-offset)',
      margin: 'var(--space-4) 0'
    }} />
  )
}

export function RowBetween({ children }: { children: React.ReactNode }) {
  return (
    <div style={{
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 'var(--space-4)'
    }}>
      {children}
    </div>
  )
}
