import { useWallDocument } from './useWallDocument'
import { useWallPointer } from './useWallPointer'
import { useWallKeys } from './useWallKeys'
export type { Menu } from './useWallDocument'

/** drags paint the DOM between renders, hence the refs */
export function useWallView() {
  const wallDocument = useWallDocument()
  const wallPointer = useWallPointer(wallDocument)
  const wallKeys = useWallKeys(wallDocument, wallPointer)
  const {
    setView, setPendingNoteTitle, doc, cards, notes, loading, selectedIds, setSelectedIds, editingId,
    setEditingId, picker, setPicker, menu, setMenu, snapping, setSnapping, tool, setTool, penColor,
    setPenColor, penWidth, setPenWidth, smoothing, setSmoothing, drawing, arrowFrom, setArrowFrom,
    arrowDrag, arrowEndHover, arrowShape, setArrowShape, arrowLine, setArrowLine, arrowHeads,
    setArrowHeads, marquee, busy, query, setQuery, wallMenuOpen, setWallMenuOpen, renaming,
    setRenaming, pendingDelete, setPendingDelete, railOpen, railWidth, setRailWidth, railTab,
    setRailTab, railQuery, setRailQuery, columns, dropColumnId, bgOpen, setBgOpen, shortcutsOpen,
    setShortcutsOpen, spaceHeld, swatchOpen, setSwatchOpen, keys, panButtons, menuButton,
    viewportRef, marqueeRectRef, fileInputRef, docRef, historyRef, cardsById, itemsById,
    notesByTitle, selectedItems, single, arrowsSelected, wallIndex, activeWall, commitIndex, addWall,
    setBackground, toggleRail, confirmDeleteWall, setItems, setCamera, onItemTextChange,
    onItemFinishEditing, applyHistory, addItem, removeSelected, duplicateSelected, toggleLock,
    openCard, placeImageFiles
  } = wallDocument
  const {
    screenPoint, onWheel, jumpTo, exportPng, fitToContent, arrowAt, onPointerDown, onPointerMove,
    endDrag
  } = wallPointer
  const {
    menuEntries, camera, custom, canvasBackground, dotColor, placed, pickerRows, labelOf, matches,
    undoable, redoable, floatingRef, floatingPos
  } = wallKeys

  return {
    setView,
    setPendingNoteTitle,
    doc,
    cards,
    notes,
    loading,
    selectedIds,
    setSelectedIds,
    editingId,
    setEditingId,
    picker,
    setPicker,
    menu,
    setMenu,
    snapping,
    setSnapping,
    tool,
    setTool,
    penColor,
    setPenColor,
    penWidth,
    setPenWidth,
    smoothing,
    setSmoothing,
    drawing,
    arrowFrom,
    setArrowFrom,
    arrowDrag,
    arrowEndHover,
    arrowShape,
    setArrowShape,
    arrowLine,
    setArrowLine,
    arrowHeads,
    setArrowHeads,
    marquee,
    busy,
    query,
    setQuery,
    wallMenuOpen,
    setWallMenuOpen,
    renaming,
    setRenaming,
    pendingDelete,
    setPendingDelete,
    railOpen,
    railWidth,
    setRailWidth,
    railTab,
    setRailTab,
    railQuery,
    setRailQuery,
    columns,
    dropColumnId,
    bgOpen,
    setBgOpen,
    shortcutsOpen,
    setShortcutsOpen,
    spaceHeld,
    swatchOpen,
    setSwatchOpen,
    keys,
    panButtons,
    menuButton,
    viewportRef,
    marqueeRectRef,
    fileInputRef,
    docRef,
    historyRef,
    cardsById,
    itemsById,
    notesByTitle,
    selectedItems,
    single,
    arrowsSelected,
    wallIndex,
    activeWall,
    commitIndex,
    addWall,
    setBackground,
    toggleRail,
    confirmDeleteWall,
    setItems,
    setCamera,
    onItemTextChange,
    onItemFinishEditing,
    applyHistory,
    addItem,
    removeSelected,
    duplicateSelected,
    toggleLock,
    openCard,
    placeImageFiles,
    screenPoint,
    onWheel,
    jumpTo,
    exportPng,
    fitToContent,
    arrowAt,
    onPointerDown,
    onPointerMove,
    endDrag,
    menuEntries,
    camera,
    custom,
    canvasBackground,
    dotColor,
    placed,
    pickerRows,
    labelOf,
    matches,
    undoable,
    redoable,
    floatingRef,
    floatingPos
  }
}

export type WallViewState = ReturnType<typeof useWallView>
